# Generated by Django 5.1 on 2025-04-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='execution_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('SUCCESS', 'Success'), ('RUNNING', 'Running'), ('PENDING', 'Pending')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status', 'state'], name='core_workfl_status_f9b3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['start_time'], name='core_workfl_start_t_23df8c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['retry_count'], name='core_workfl_retry_c_d451a3_idx'),
        ),
    ]
